# Generated by Django 5.2.8 on 2025-11-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.JSONField(default=list)),
                ('instructions', models.TextField(blank=True)),
                ('cook_time_minutes', models.PositiveIntegerField(default=30)),
                ('servings', models.PositiveIntegerField(default=2)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='dinner', max_length=50)),
                ('youtube_query', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
